language:
  usage:
    - "&f&m---------------------------------"
    - "&7/team create <name>"
    - "&7/team remove <name>"
    - "&7/team invite <name>"
    - "&7/team uninvite <name>"
    - "&7/team accept <name>"
    - "&f&m---------------------------------"
  in-team: "&cYou are already in team."
  exists: "&c%team% already exists."
  validation-error: "&cTeam name cannot be shorter then 1 letter and larger then 3 letters."
  created: "&aSuccessfully created team %team%"
  not-in-team: "&cYou must be in team to perform this command."
  leader: "&cYou must be leader to perform this command."
  removed: "&aSuccessfully removed team"
  chat-enabled: "&aSuccessfully entered team chat."
  chat-disabled: "&cSuccessfully left team chat."
  leave-own-tem: "&cYou cannot leave your own team."
  left-team: "&aSuccessfully left team."
  null-player: "&cPlease specify a player."
  player-offline: "&cPlayer is currently offline."
  player-invited: "&aSuccessfully invited %player% to your team."
  player-uninvited: "&aSuccessfully uninvited %player% to your team."
  no-invitation: "&cYou don't have any team to accept invitation"
  accepted: "&aSuccessfully accepted invitation to team %team%"
  invalid-name: "&cPlease provide name for a team."
  chat-format: "&7[&eTeam&7] &e%player%&7: &f%message%"
  hurt-teammate: "&cYou cannot hurt player from your team."